window.FLASHCARD_DATA = {
  "levels": [
    {
      "id": 1,
      "name": "Level 1 - Basics",
      "description": "Essential Telugu vocabulary for beginners",
      "flashcards": [
        {"id": 1, "telugu": "నమస్కారం", "romanization": "Namaskāram", "english": "Hello/Greetings", "category": "Greetings"},
        {"id": 2, "telugu": "ధన్యవాదాలు", "romanization": "Dhanyavādālu", "english": "Thank you", "category": "Greetings"},
        {"id": 3, "telugu": "క్షమించండి", "romanization": "Kṣaminchandi", "english": "Sorry/Excuse me", "category": "Greetings"},
        {"id": 4, "telugu": "అవును", "romanization": "Avunu", "english": "Yes", "category": "Common Words"},
        {"id": 5, "telugu": "కాదు", "romanization": "Kādu", "english": "No", "category": "Common Words"},
        {"id": 6, "telugu": "దయచేసి", "romanization": "Dayachēsi", "english": "Please", "category": "Greetings"},
        {"id": 7, "telugu": "శుభోదయం", "romanization": "Śubhōdayam", "english": "Good morning", "category": "Greetings"},
        {"id": 8, "telugu": "శుభ రాత్రి", "romanization": "Śubha rātri", "english": "Good night", "category": "Greetings"},
        {"id": 9, "telugu": "ఒకటి", "romanization": "Okaṭi", "english": "One", "category": "Numbers"},
        {"id": 10, "telugu": "రెండు", "romanization": "Reṇḍu", "english": "Two", "category": "Numbers"},
        {"id": 11, "telugu": "మూడు", "romanization": "Mūḍu", "english": "Three", "category": "Numbers"},
        {"id": 12, "telugu": "నాలుగు", "romanization": "Nālugu", "english": "Four", "category": "Numbers"},
        {"id": 13, "telugu": "ఐదు", "romanization": "Aidu", "english": "Five", "category": "Numbers"},
        {"id": 14, "telugu": "ఆరు", "romanization": "Āru", "english": "Six", "category": "Numbers"},
        {"id": 15, "telugu": "ఏడు", "romanization": "Ēḍu", "english": "Seven", "category": "Numbers"},
        {"id": 16, "telugu": "ఎనిమిది", "romanization": "Enimidi", "english": "Eight", "category": "Numbers"},
        {"id": 17, "telugu": "తొమ్మిది", "romanization": "Tommidi", "english": "Nine", "category": "Numbers"},
        {"id": 18, "telugu": "పది", "romanization": "Padi", "english": "Ten", "category": "Numbers"},
        {"id": 19, "telugu": "తల్లి", "romanization": "Talli", "english": "Mother", "category": "Family"},
        {"id": 20, "telugu": "తండ్రి", "romanization": "Taṇḍri", "english": "Father", "category": "Family"},
        {"id": 21, "telugu": "అన్న", "romanization": "Anna", "english": "Elder brother", "category": "Family"},
        {"id": 22, "telugu": "అక్ka", "romanization": "Akka", "english": "Elder sister", "category": "Family"},
        {"id": 23, "telugu": "తమ్ముడు", "romanization": "Tammuḍu", "english": "Younger brother", "category": "Family"},
        {"id": 24, "telugu": "చెల్లెలు", "romanization": "Chellelu", "english": "Younger sister", "category": "Family"},
        {"id": 25, "telugu": "తాత", "romanization": "Tāta", "english": "Grandfather", "category": "Family"},
        {"id": 26, "telugu": "అమ్మమ్మ", "romanization": "Ammamma", "english": "Grandmother", "category": "Family"},
        {"id": 27, "telugu": "నేను", "romanization": "Nēnu", "english": "I/Me", "category": "Pronouns"},
        {"id": 28, "telugu": "నువ్వు", "romanization": "Nuvvu", "english": "You", "category": "Pronouns"},
        {"id": 29, "telugu": "అతను", "romanization": "Atanu", "english": "He", "category": "Pronouns"},
        {"id": 30, "telugu": "ఆమె", "romanization": "Āme", "english": "She", "category": "Pronouns"},
        {"id": 31, "telugu": "మనం", "romanization": "Manam", "english": "We", "category": "Pronouns"},
        {"id": 32, "telugu": "వారు", "romanization": "Vāru", "english": "They", "category": "Pronouns"},
        {"id": 33, "telugu": "తినండి", "romanization": "Tinaṇḍi", "english": "Eat", "category": "Verbs"},
        {"id": 34, "telugu": "త్రాగండి", "romanization": "Trāgaṇḍi", "english": "Drink", "category": "Verbs"},
        {"id": 35, "telugu": "వెళ్ళండి", "romanization": "Veḷḷaṇḍi", "english": "Go", "category": "Verbs"},
        {"id": 36, "telugu": "రండి", "romanization": "Raṇḍi", "english": "Come", "category": "Verbs"},
        {"id": 37, "telugu": "చదవండి", "romanization": "Chadavaṇḍi", "english": "Read", "category": "Verbs"},
        {"id": 38, "telugu": "వ్రాయండి", "romanization": "Vrāyaṇḍi", "english": "Write", "category": "Verbs"},
        {"id": 39, "telugu": "మాట్లాడండి", "romanization": "Māṭlāḍaṇḍi", "english": "Speak", "category": "Verbs"},
        {"id": 40, "telugu": "వినండి", "romanization": "Vinaṇḍi", "english": "Listen", "category": "Verbs"},
        {"id": 41, "telugu": "చూడండి", "romanization": "Chūḍaṇḍi", "english": "See/Look", "category": "Verbs"},
        {"id": 42, "telugu": "నిద్రపోండి", "romanization": "Nidrapōṇḍi", "english": "Sleep", "category": "Verbs"},
        {"id": 43, "telugu": "నీళ్ళు", "romanization": "Nīḷḷu", "english": "Water", "category": "Common Words"},
        {"id": 44, "telugu": "ఆహారం", "romanization": "Āhāram", "english": "Food", "category": "Common Words"},
        {"id": 45, "telugu": "ఇల్లు", "romanization": "Illu", "english": "House", "category": "Places"},
        {"id": 46, "telugu": "పాఠశాల", "romanization": "Pāṭhaśāla", "english": "School", "category": "Places"},
        {"id": 47, "telugu": "పుస్తకం", "romanization": "Pustakam", "english": "Book", "category": "Common Words"},
        {"id": 48, "telugu": "పేరు", "romanization": "Pēru", "english": "Name", "category": "Common Words"},
        {"id": 49, "telugu": "రోజు", "romanization": "Rōju", "english": "Day", "category": "Time"},
        {"id": 50, "telugu": "రాత్రి", "romanization": "Rātri", "english": "Night", "category": "Time"},
        {"id": 51, "telugu": "ఉదయం", "romanization": "Udayam", "english": "Morning", "category": "Time"},
        {"id": 52, "telugu": "సాయంత్రం", "romanization": "Sāyantram", "english": "Evening", "category": "Time"},
        {"id": 53, "telugu": "ఎలా", "romanization": "Elā", "english": "How", "category": "Questions"},
        {"id": 54, "telugu": "ఎక్కడ", "romanization": "Ekkaḍa", "english": "Where", "category": "Questions"},
        {"id": 55, "telugu": "ఎప్పుడు", "romanization": "Eppuḍu", "english": "When", "category": "Questions"},
        {"id": 56, "telugu": "ఎవరు", "romanization": "Evaru", "english": "Who", "category": "Questions"},
        {"id": 57, "telugu": "ఏమి", "romanization": "Ēmi", "english": "What", "category": "Questions"},
        {"id": 58, "telugu": "ఎందుకు", "romanization": "Enduku", "english": "Why", "category": "Questions"},
        {"id": 59, "telugu": "పెద్ద", "romanization": "Pedda", "english": "Big", "category": "Adjectives"},
        {"id": 60, "telugu": "చిన్న", "romanization": "Chinna", "english": "Small", "category": "Adjectives"},
        {"id": 61, "telugu": "మంచి", "romanization": "Manchi", "english": "Good", "category": "Adjectives"},
        {"id": 62, "telugu": "చెడు", "romanization": "Cheḍu", "english": "Bad", "category": "Adjectives"},
        {"id": 63, "telugu": "కొత్త", "romanization": "Kotta", "english": "New", "category": "Adjectives"},
        {"id": 64, "telugu": "పాత", "romanization": "Pāta", "english": "Old", "category": "Adjectives"},
        {"id": 65, "telugu": "అందమైన", "romanization": "Andamaina", "english": "Beautiful", "category": "Adjectives"},
        {"id": 66, "telugu": "తెలుపు", "romanization": "Telupu", "english": "White", "category": "Colors"},
        {"id": 67, "telugu": "నలుపు", "romanization": "Nalupu", "english": "Black", "category": "Colors"},
        {"id": 68, "telugu": "ఎరుపు", "romanization": "Erupu", "english": "Red", "category": "Colors"},
        {"id": 69, "telugu": "నీలం", "romanization": "Nīlam", "english": "Blue", "category": "Colors"},
        {"id": 70, "telugu": "ఆకుపచ్చ", "romanization": "Ākupachcha", "english": "Green", "category": "Colors"},
        {"id": 71, "telugu": "పసుపు", "romanization": "Pasupu", "english": "Yellow", "category": "Colors"},
        {"id": 72, "telugu": "తల", "romanization": "Tala", "english": "Head", "category": "Body Parts"},
        {"id": 73, "telugu": "కన్ను", "romanization": "Kannu", "english": "Eye", "category": "Body Parts"},
        {"id": 74, "telugu": "చెవి", "romanization": "Chevi", "english": "Ear", "category": "Body Parts"},
        {"id": 75, "telugu": "ముక్కు", "romanization": "Mukku", "english": "Nose", "category": "Body Parts"},
        {"id": 76, "telugu": "నోరు", "romanization": "Nōru", "english": "Mouth", "category": "Body Parts"},
        {"id": 77, "telugu": "చేయి", "romanization": "Chēyi", "english": "Hand", "category": "Body Parts"},
        {"id": 78, "telugu": "కాలు", "romanization": "Kālu", "english": "Leg", "category": "Body Parts"},
        {"id": 79, "telugu": "హృదయం", "romanization": "Hṛdayam", "english": "Heart", "category": "Body Parts"},
        {"id": 80, "telugu": "ఆసుపత్రి", "romanization": "Āsupatri", "english": "Hospital", "category": "Places"},
        {"id": 81, "telugu": "దుకాణం", "romanization": "Dukāṇam", "english": "Shop", "category": "Places"},
        {"id": 82, "telugu": "ఆలయం", "romanization": "Ālayam", "english": "Temple", "category": "Places"},
        {"id": 83, "telugu": "మార్కెట్", "romanization": "Mārkeṭ", "english": "Market", "category": "Places"},
        {"id": 84, "telugu": "కారు", "romanization": "Kāru", "english": "Car", "category": "Common Words"},
        {"id": 85, "telugu": "బస్సు", "romanization": "Bassu", "english": "Bus", "category": "Common Words"},
        {"id": 86, "telugu": "రైలు", "romanization": "Railu", "english": "Train", "category": "Common Words"},
        {"id": 87, "telugu": "డబ్బు", "romanization": "Ḍabbu", "english": "Money", "category": "Common Words"},
        {"id": 88, "telugu": "సమయం", "romanization": "Samayam", "english": "Time", "category": "Time"},
        {"id": 89, "telugu": "స్నేహితుడు", "romanization": "Snēhituḍu", "english": "Friend (male)", "category": "Common Words"},
        {"id": 90, "telugu": "స్నేహితురాలు", "romanization": "Snēhiturālu", "english": "Friend (female)", "category": "Common Words"},
        {"id": 91, "telugu": "ప్రేమ", "romanization": "Prēma", "english": "Love", "category": "Common Words"},
        {"id": 92, "telugu": "ఆనందం", "romanization": "Ānandam", "english": "Happiness", "category": "Common Words"},
        {"id": 93, "telugu": "దుఃఖం", "romanization": "Duḥkham", "english": "Sadness", "category": "Common Words"},
        {"id": 94, "telugu": "భాష", "romanization": "Bhāsha", "english": "Language", "category": "Common Words"},
        {"id": 95, "telugu": "దేశం", "romanization": "Dēśam", "english": "Country", "category": "Places"},
        {"id": 96, "telugu": "నగరం", "romanization": "Nagaram", "english": "City", "category": "Places"},
        {"id": 97, "telugu": "గ్రామం", "romanization": "Grāmam", "english": "Village", "category": "Places"},
        {"id": 98, "telugu": "వాతావరణం", "romanization": "Vātāvaraṇam", "english": "Weather", "category": "Common Words"},
        {"id": 99, "telugu": "వర్షం", "romanization": "Varṣam", "english": "Rain", "category": "Common Words"},
        {"id": 100, "telugu": "ఎండ", "romanization": "Eṇḍa", "english": "Sun/Heat", "category": "Common Words"}
      ]
    },
    {
      "id": 2,
      "name": "Level 2 - Intermediate",
      "description": "Intermediate Telugu vocabulary for daily conversations",
      "flashcards": [
        {"id": 101, "telugu": "పదకొండు", "romanization": "Padakoṇḍu", "english": "Eleven", "category": "Numbers"},
        {"id": 102, "telugu": "పన్నెండు", "romanization": "Panneṇḍu", "english": "Twelve", "category": "Numbers"},
        {"id": 103, "telugu": "పదమూడు", "romanization": "Padamūḍu", "english": "Thirteen", "category": "Numbers"},
        {"id": 104, "telugu": "పద్నాలుగు", "romanization": "Padnālugu", "english": "Fourteen", "category": "Numbers"},
        {"id": 105, "telugu": "పదిహేను", "romanization": "Padihēnu", "english": "Fifteen", "category": "Numbers"},
        {"id": 106, "telugu": "ఇరవై", "romanization": "Iravai", "english": "Twenty", "category": "Numbers"},
        {"id": 107, "telugu": "ముప్పై", "romanization": "Muppai", "english": "Thirty", "category": "Numbers"},
        {"id": 108, "telugu": "వంద", "romanization": "Vaṃda", "english": "Hundred", "category": "Numbers"},
        {"id": 109, "telugu": "వేయి", "romanization": "Vēyi", "english": "Thousand", "category": "Numbers"},
        {"id": 110, "telugu": "మామ", "romanization": "Māma", "english": "Uncle (maternal)", "category": "Family"},
        {"id": 111, "telugu": "పిన్ని", "romanization": "Pinni", "english": "Aunt (paternal)", "category": "Family"},
        {"id": 112, "telugu": "అత్త", "romanization": "Atta", "english": "Aunt (maternal)", "category": "Family"},
        {"id": 113, "telugu": "కొడుకు", "romanization": "Koḍuku", "english": "Son", "category": "Family"},
        {"id": 114, "telugu": "కూతురు", "romanization": "Kūturu", "english": "Daughter", "category": "Family"},
        {"id": 115, "telugu": "భార్య", "romanization": "Bhārya", "english": "Wife", "category": "Family"},
        {"id": 116, "telugu": "భర్త", "romanization": "Bharta", "english": "Husband", "category": "Family"},
        {"id": 117, "telugu": "కొనండి", "romanization": "Konaṇḍi", "english": "Buy", "category": "Verbs"},
        {"id": 118, "telugu": "అమ్మండి", "romanization": "Ammaṇḍi", "english": "Sell", "category": "Verbs"},
        {"id": 119, "telugu": "సహాయం చేయండి", "romanization": "Sahāyaṃ chēyaṇḍi", "english": "Help", "category": "Verbs"},
        {"id": 120, "telugu": "నేర్చుకోండి", "romanization": "Nērchukoṇḍi", "english": "Learn", "category": "Verbs"},
        {"id": 121, "telugu": "నేర్పండి", "romanization": "Nērpaṇḍi", "english": "Teach", "category": "Verbs"},
        {"id": 122, "telugu": "పని చేయండి", "romanization": "Pani chēyaṇḍi", "english": "Work", "category": "Verbs"},
        {"id": 123, "telugu": "ఆడండి", "romanization": "Āḍaṇḍi", "english": "Play", "category": "Verbs"},
        {"id": 124, "telugu": "పరుగెత్తండి", "romanization": "Paruget taṇḍi", "english": "Run", "category": "Verbs"},
        {"id": 125, "telugu": "నడవండి", "romanization": "Naḍavaṇḍi", "english": "Walk", "category": "Verbs"},
        {"id": 126, "telugu": "కూర్చోండి", "romanization": "Kūrchōṇḍi", "english": "Sit", "category": "Verbs"},
        {"id": 127, "telugu": "నిలబడండి", "romanization": "Nilabaḍaṇḍi", "english": "Stand", "category": "Verbs"},
        {"id": 128, "telugu": "తెరవండి", "romanization": "Teravaṇḍi", "english": "Open", "category": "Verbs"},
        {"id": 129, "telugu": "మూసివేయండి", "romanization": "Mūsivēyaṇḍi", "english": "Close", "category": "Verbs"},
        {"id": 130, "telugu": "ఇవ్వండి", "romanization": "Ivvaṇḍi", "english": "Give", "category": "Verbs"},
        {"id": 131, "telugu": "తీసుకోండి", "romanization": "Tīsukoṇḍi", "english": "Take", "category": "Verbs"},
        {"id": 132, "telugu": "వంట చేయండి", "romanization": "Vaṇṭa chēyaṇḍi", "english": "Cook", "category": "Verbs"},
        {"id": 133, "telugu": "అడగండి", "romanization": "Aḍagaṇḍi", "english": "Ask", "category": "Verbs"},
        {"id": 134, "telugu": "సోమవారం", "romanization": "Sōmavāraṃ", "english": "Monday", "category": "Time"},
        {"id": 135, "telugu": "మంగళవారం", "romanization": "Maṅgaḷavāraṃ", "english": "Tuesday", "category": "Time"},
        {"id": 136, "telugu": "బుధవారం", "romanization": "Budhavāraṃ", "english": "Wednesday", "category": "Time"},
        {"id": 137, "telugu": "గురువారం", "romanization": "Guruvāraṃ", "english": "Thursday", "category": "Time"},
        {"id": 138, "telugu": "శుక్రవారం", "romanization": "Śukravāraṃ", "english": "Friday", "category": "Time"},
        {"id": 139, "telugu": "శనివారం", "romanization": "Śanivāraṃ", "english": "Saturday", "category": "Time"},
        {"id": 140, "telugu": "ఆదివారం", "romanization": "Ādivāraṃ", "english": "Sunday", "category": "Time"},
        {"id": 141, "telugu": "వారం", "romanization": "Vāraṃ", "english": "Week", "category": "Time"},
        {"id": 142, "telugu": "నెల", "romanization": "Nela", "english": "Month", "category": "Time"},
        {"id": 143, "telugu": "సంవత్సరం", "romanization": "Saṃvatsaraṃ", "english": "Year", "category": "Time"},
        {"id": 144, "telugu": "నిన్న", "romanization": "Ninna", "english": "Yesterday", "category": "Time"},
        {"id": 145, "telugu": "ఈ రోజు", "romanization": "Ī rōju", "english": "Today", "category": "Time"},
        {"id": 146, "telugu": "రేపు", "romanization": "Rēpu", "english": "Tomorrow", "category": "Time"},
        {"id": 147, "telugu": "వేడి", "romanization": "Vēḍi", "english": "Hot", "category": "Adjectives"},
        {"id": 148, "telugu": "చల్లని", "romanization": "Challani", "english": "Cold", "category": "Adjectives"},
        {"id": 149, "telugu": "పొడవైన", "romanization": "Poḍavaina", "english": "Tall/Long", "category": "Adjectives"},
        {"id": 150, "telugu": "పొట్టి", "romanization": "Poṭṭi", "english": "Short", "category": "Adjectives"},
        {"id": 151, "telugu": "వేగమైన", "romanization": "Vēgamaina", "english": "Fast", "category": "Adjectives"},
        {"id": 152, "telugu": "నెమ్మదిగా", "romanization": "Nemmadigā", "english": "Slow", "category": "Adjectives"},
        {"id": 153, "telugu": "సంతోషంగా", "romanization": "Santōṣaṅgā", "english": "Happy", "category": "Adjectives"},
        {"id": 154, "telugu": "బాధగా", "romanization": "Bādhagā", "english": "Sad", "category": "Adjectives"},
        {"id": 155, "telugu": "కోపంగా", "romanization": "Kōpaṅgā", "english": "Angry", "category": "Adjectives"},
        {"id": 156, "telugu": "రుచికరమైన", "romanization": "Ruchikaramaina", "english": "Delicious/Tasty", "category": "Adjectives"},
        {"id": 157, "telugu": "శుభ్రమైన", "romanization": "Śubhramaina", "english": "Clean", "category": "Adjectives"},
        {"id": 158, "telugu": "మురికి", "romanization": "Muriki", "english": "Dirty", "category": "Adjectives"},
        {"id": 159, "telugu": "చొక్కా", "romanization": "Chokkā", "english": "Shirt", "category": "Common Words"},
        {"id": 160, "telugu": "పంట", "romanization": "Paṇṭa", "english": "Pants", "category": "Common Words"},
        {"id": 161, "telugu": "చీరె", "romanization": "Chīre", "english": "Saree", "category": "Common Words"},
        {"id": 162, "telugu": "బూట్లు", "romanization": "Būṭlu", "english": "Shoes", "category": "Common Words"},
        {"id": 163, "telugu": "అన్నం", "romanization": "Annaṃ", "english": "Rice/Food", "category": "Common Words"},
        {"id": 164, "telugu": "కూర", "romanization": "Kūra", "english": "Curry/Vegetable", "category": "Common Words"},
        {"id": 165, "telugu": "రొట్టె", "romanization": "Roṭṭe", "english": "Bread", "category": "Common Words"},
        {"id": 166, "telugu": "పాలు", "romanization": "Pālu", "english": "Milk", "category": "Common Words"},
        {"id": 167, "telugu": "చాయ", "romanization": "Chāya", "english": "Tea", "category": "Common Words"},
        {"id": 168, "telugu": "కాఫీ", "romanization": "Kāphī", "english": "Coffee", "category": "Common Words"},
        {"id": 169, "telugu": "పండు", "romanization": "Paṇḍu", "english": "Fruit", "category": "Common Words"},
        {"id": 170, "telugu": "కూరగాయలు", "romanization": "Kūragāyalu", "english": "Vegetables", "category": "Common Words"},
        {"id": 171, "telugu": "మాంసం", "romanization": "Māṃsaṃ", "english": "Meat", "category": "Common Words"},
        {"id": 172, "telugu": "చేప", "romanization": "Chēpa", "english": "Fish", "category": "Common Words"},
        {"id": 173, "telugu": "గుడ్డు", "romanization": "Guḍḍu", "english": "Egg", "category": "Common Words"},
        {"id": 174, "telugu": "ఉప్పు", "romanization": "Uppu", "english": "Salt", "category": "Common Words"},
        {"id": 175, "telugu": "పంచదార", "romanization": "Pañchadāra", "english": "Sugar", "category": "Common Words"},
        {"id": 176, "telugu": "నూనె", "romanization": "Nūne", "english": "Oil", "category": "Common Words"},
        {"id": 177, "telugu": "కుడి", "romanization": "Kuḍi", "english": "Right (direction)", "category": "Common Words"},
        {"id": 178, "telugu": "ఎడమ", "romanization": "Eḍama", "english": "Left (direction)", "category": "Common Words"},
        {"id": 179, "telugu": "నేరుగా", "romanization": "Nērugā", "english": "Straight", "category": "Common Words"},
        {"id": 180, "telugu": "వెనుక", "romanization": "Venuka", "english": "Back/Behind", "category": "Common Words"},
        {"id": 181, "telugu": "ముందు", "romanization": "Mundu", "english": "Front", "category": "Common Words"},
        {"id": 182, "telugu": "పైన", "romanization": "Paina", "english": "Above/Up", "category": "Common Words"},
        {"id": 183, "telugu": "క్రింద", "romanization": "Krinda", "english": "Below/Down", "category": "Common Words"},
        {"id": 184, "telugu": "డాక్టర్", "romanization": "Ḍākṭar", "english": "Doctor", "category": "Common Words"},
        {"id": 185, "telugu": "టీచర్", "romanization": "Ṭīchar", "english": "Teacher", "category": "Common Words"},
        {"id": 186, "telugu": "ఇంజనీర్", "romanization": "Iṃjanīr", "english": "Engineer", "category": "Common Words"},
        {"id": 187, "telugu": "విద్యార్థి", "romanization": "Vidyārthi", "english": "Student", "category": "Common Words"},
        {"id": 188, "telugu": "రైతు", "romanization": "Raitu", "english": "Farmer", "category": "Common Words"},
        {"id": 189, "telugu": "డ్రైవర్", "romanization": "Ḍraivar", "english": "Driver", "category": "Common Words"},
        {"id": 190, "telugu": "తెలివైన", "romanization": "Telivaina", "english": "Intelligent/Smart", "category": "Adjectives"},
        {"id": 191, "telugu": "అద్భుతమైన", "romanization": "Adbhutamaina", "english": "Wonderful/Amazing", "category": "Adjectives"},
        {"id": 192, "telugu": "కష్టం", "romanization": "Kaṣṭaṃ", "english": "Difficult/Hard", "category": "Adjectives"},
        {"id": 193, "telugu": "సులభం", "romanization": "Sulabhaṃ", "english": "Easy", "category": "Adjectives"},
        {"id": 194, "telugu": "బలమైన", "romanization": "Balamaina", "english": "Strong", "category": "Adjectives"},
        {"id": 195, "telugu": "బలహీనమైన", "romanization": "Balahīnamaina", "english": "Weak", "category": "Adjectives"},
        {"id": 196, "telugu": "నిజం", "romanization": "Nijaṃ", "english": "True/Truth", "category": "Common Words"},
        {"id": 197, "telugu": "అబద్ధం", "romanization": "Abaddhaṃ", "english": "Lie/False", "category": "Common Words"},
        {"id": 198, "telugu": "ప్రశ్న", "romanization": "Praśna", "english": "Question", "category": "Common Words"},
        {"id": 199, "telugu": "జవాబు", "romanization": "Javābu", "english": "Answer", "category": "Common Words"},
        {"id": 200, "telugu": "సమస్య", "romanization": "Samasya", "english": "Problem", "category": "Common Words"}
      ]
    }
  ]
};
