window.FLASHCARD_DATA = {
  "levels": [
    {
      "id": 1,
      "name": "Level 1 - Basics",
      "description": "Essential Hindi vocabulary for beginners",
      "flashcards": [
        {"id": 1, "hindi": "नमस्ते", "romanization": "Namaste", "english": "Hello/Greetings", "category": "Greetings"},
        {"id": 2, "hindi": "धन्यवाद", "romanization": "Dhanyavād", "english": "Thank you", "category": "Greetings"},
        {"id": 3, "hindi": "माफ़ कीजिए", "romanization": "Māf kījie", "english": "Sorry/Excuse me", "category": "Greetings"},
        {"id": 4, "hindi": "हाँ", "romanization": "Hāṅ", "english": "Yes", "category": "Common Words"},
        {"id": 5, "hindi": "नहीं", "romanization": "Nahīṅ", "english": "No", "category": "Common Words"},
        {"id": 6, "hindi": "कृपया", "romanization": "Kr̥payā", "english": "Please", "category": "Greetings"},
        {"id": 7, "hindi": "सुप्रभात", "romanization": "Suprabhāt", "english": "Good morning", "category": "Greetings"},
        {"id": 8, "hindi": "शुभ रात्रि", "romanization": "Śubh rātri", "english": "Good night", "category": "Greetings"},
        {"id": 9, "hindi": "अलविदा", "romanization": "Alvidā", "english": "Goodbye", "category": "Greetings"},
        {"id": 10, "hindi": "स्वागत है", "romanization": "Svāgat hai", "english": "Welcome", "category": "Greetings"},

        {"id": 11, "hindi": "एक", "romanization": "Ek", "english": "One", "category": "Numbers"},
        {"id": 12, "hindi": "दो", "romanization": "Do", "english": "Two", "category": "Numbers"},
        {"id": 13, "hindi": "तीन", "romanization": "Tīn", "english": "Three", "category": "Numbers"},
        {"id": 14, "hindi": "चार", "romanization": "Chār", "english": "Four", "category": "Numbers"},
        {"id": 15, "hindi": "पाँच", "romanization": "Pāṅch", "english": "Five", "category": "Numbers"},
        {"id": 16, "hindi": "छह", "romanization": "Chhah", "english": "Six", "category": "Numbers"},
        {"id": 17, "hindi": "सात", "romanization": "Sāt", "english": "Seven", "category": "Numbers"},
        {"id": 18, "hindi": "आठ", "romanization": "Āṭh", "english": "Eight", "category": "Numbers"},
        {"id": 19, "hindi": "नौ", "romanization": "Nau", "english": "Nine", "category": "Numbers"},
        {"id": 20, "hindi": "दस", "romanization": "Das", "english": "Ten", "category": "Numbers"},

        {"id": 21, "hindi": "माता", "romanization": "Mātā", "english": "Mother", "category": "Family"},
        {"id": 22, "hindi": "पिता", "romanization": "Pitā", "english": "Father", "category": "Family"},
        {"id": 23, "hindi": "भाई", "romanization": "Bhāī", "english": "Brother", "category": "Family"},
        {"id": 24, "hindi": "बहन", "romanization": "Bahan", "english": "Sister", "category": "Family"},
        {"id": 25, "hindi": "दादा", "romanization": "Dādā", "english": "Grandfather (paternal)", "category": "Family"},
        {"id": 26, "hindi": "दादी", "romanization": "Dādī", "english": "Grandmother (paternal)", "category": "Family"},
        {"id": 27, "hindi": "नाना", "romanization": "Nānā", "english": "Grandfather (maternal)", "category": "Family"},
        {"id": 28, "hindi": "नानी", "romanization": "Nānī", "english": "Grandmother (maternal)", "category": "Family"},
        {"id": 29, "hindi": "बेटा", "romanization": "Beṭā", "english": "Son", "category": "Family"},
        {"id": 30, "hindi": "बेटी", "romanization": "Beṭī", "english": "Daughter", "category": "Family"},

        {"id": 31, "hindi": "मैं", "romanization": "Main", "english": "I/Me", "category": "Pronouns"},
        {"id": 32, "hindi": "तुम", "romanization": "Tum", "english": "You (informal)", "category": "Pronouns"},
        {"id": 33, "hindi": "आप", "romanization": "Āp", "english": "You (formal)", "category": "Pronouns"},
        {"id": 34, "hindi": "वह", "romanization": "Vah", "english": "He/She/It", "category": "Pronouns"},
        {"id": 35, "hindi": "हम", "romanization": "Ham", "english": "We", "category": "Pronouns"},
        {"id": 36, "hindi": "वे", "romanization": "Ve", "english": "They", "category": "Pronouns"},
        {"id": 37, "hindi": "यह", "romanization": "Yah", "english": "This", "category": "Pronouns"},
        {"id": 38, "hindi": "वो", "romanization": "Vo", "english": "That", "category": "Pronouns"},

        {"id": 39, "hindi": "खाना", "romanization": "Khānā", "english": "Eat/Food", "category": "Verbs"},
        {"id": 40, "hindi": "पीना", "romanization": "Pīnā", "english": "Drink", "category": "Verbs"},
        {"id": 41, "hindi": "जाना", "romanization": "Jānā", "english": "Go", "category": "Verbs"},
        {"id": 42, "hindi": "आना", "romanization": "Ānā", "english": "Come", "category": "Verbs"},
        {"id": 43, "hindi": "पढ़ना", "romanization": "Paṛhnā", "english": "Read", "category": "Verbs"},
        {"id": 44, "hindi": "लिखना", "romanization": "Likhnā", "english": "Write", "category": "Verbs"},
        {"id": 45, "hindi": "बोलना", "romanization": "Bolnā", "english": "Speak", "category": "Verbs"},
        {"id": 46, "hindi": "सुनना", "romanization": "Sunnā", "english": "Listen", "category": "Verbs"},
        {"id": 47, "hindi": "देखना", "romanization": "Dekhnā", "english": "See/Look", "category": "Verbs"},
        {"id": 48, "hindi": "सोना", "romanization": "Sonā", "english": "Sleep", "category": "Verbs"},

        {"id": 49, "hindi": "पानी", "romanization": "Pānī", "english": "Water", "category": "Common Words"},
        {"id": 50, "hindi": "नाम", "romanization": "Nām", "english": "Name", "category": "Common Words"},
        {"id": 51, "hindi": "घर", "romanization": "Ghar", "english": "Home/House", "category": "Common Words"},
        {"id": 52, "hindi": "दिन", "romanization": "Din", "english": "Day", "category": "Common Words"},
        {"id": 53, "hindi": "रात", "romanization": "Rāt", "english": "Night", "category": "Common Words"},
        {"id": 54, "hindi": "समय", "romanization": "Samay", "english": "Time", "category": "Common Words"},
        {"id": 55, "hindi": "लोग", "romanization": "Log", "english": "People", "category": "Common Words"},
        {"id": 56, "hindi": "आदमी", "romanization": "Ādmī", "english": "Man", "category": "Common Words"},
        {"id": 57, "hindi": "औरत", "romanization": "Aurat", "english": "Woman", "category": "Common Words"},
        {"id": 58, "hindi": "बच्चा", "romanization": "Bachchā", "english": "Child", "category": "Common Words"},

        {"id": 59, "hindi": "लाल", "romanization": "Lāl", "english": "Red", "category": "Colors"},
        {"id": 60, "hindi": "नीला", "romanization": "Nīlā", "english": "Blue", "category": "Colors"},
        {"id": 61, "hindi": "हरा", "romanization": "Harā", "english": "Green", "category": "Colors"},
        {"id": 62, "hindi": "पीला", "romanization": "Pīlā", "english": "Yellow", "category": "Colors"},
        {"id": 63, "hindi": "काला", "romanization": "Kālā", "english": "Black", "category": "Colors"},
        {"id": 64, "hindi": "सफ़ेद", "romanization": "Safed", "english": "White", "category": "Colors"},
        {"id": 65, "hindi": "गुलाबी", "romanization": "Gulābī", "english": "Pink", "category": "Colors"},
        {"id": 66, "hindi": "नारंगी", "romanization": "Nāraṅgī", "english": "Orange", "category": "Colors"},

        {"id": 67, "hindi": "बड़ा", "romanization": "Baṛā", "english": "Big/Large", "category": "Adjectives"},
        {"id": 68, "hindi": "छोटा", "romanization": "Chhoṭā", "english": "Small", "category": "Adjectives"},
        {"id": 69, "hindi": "अच्छा", "romanization": "Achchhā", "english": "Good", "category": "Adjectives"},
        {"id": 70, "hindi": "बुरा", "romanization": "Burā", "english": "Bad", "category": "Adjectives"},
        {"id": 71, "hindi": "नया", "romanization": "Nayā", "english": "New", "category": "Adjectives"},
        {"id": 72, "hindi": "पुराना", "romanization": "Purānā", "english": "Old", "category": "Adjectives"},
        {"id": 73, "hindi": "सुंदर", "romanization": "Sundar", "english": "Beautiful", "category": "Adjectives"},
        {"id": 74, "hindi": "गरम", "romanization": "Garam", "english": "Hot", "category": "Adjectives"},
        {"id": 75, "hindi": "ठंडा", "romanization": "Ṭhaṇḍā", "english": "Cold", "category": "Adjectives"},

        {"id": 76, "hindi": "सिर", "romanization": "Sir", "english": "Head", "category": "Body Parts"},
        {"id": 77, "hindi": "आँख", "romanization": "Āṅkh", "english": "Eye", "category": "Body Parts"},
        {"id": 78, "hindi": "कान", "romanization": "Kān", "english": "Ear", "category": "Body Parts"},
        {"id": 79, "hindi": "नाक", "romanization": "Nāk", "english": "Nose", "category": "Body Parts"},
        {"id": 80, "hindi": "मुँह", "romanization": "Muṅh", "english": "Mouth", "category": "Body Parts"},
        {"id": 81, "hindi": "हाथ", "romanization": "Hāth", "english": "Hand", "category": "Body Parts"},
        {"id": 82, "hindi": "पैर", "romanization": "Pair", "english": "Foot/Leg", "category": "Body Parts"},

        {"id": 83, "hindi": "क्या", "romanization": "Kyā", "english": "What", "category": "Questions"},
        {"id": 84, "hindi": "कौन", "romanization": "Kaun", "english": "Who", "category": "Questions"},
        {"id": 85, "hindi": "कहाँ", "romanization": "Kahāṅ", "english": "Where", "category": "Questions"},
        {"id": 86, "hindi": "कब", "romanization": "Kab", "english": "When", "category": "Questions"},
        {"id": 87, "hindi": "क्यों", "romanization": "Kyoṅ", "english": "Why", "category": "Questions"},
        {"id": 88, "hindi": "कैसे", "romanization": "Kaise", "english": "How", "category": "Questions"},
        {"id": 89, "hindi": "कितना", "romanization": "Kitnā", "english": "How much/How many", "category": "Questions"},

        {"id": 90, "hindi": "आज", "romanization": "Āj", "english": "Today", "category": "Time"},
        {"id": 91, "hindi": "कल", "romanization": "Kal", "english": "Yesterday/Tomorrow", "category": "Time"},
        {"id": 92, "hindi": "अभी", "romanization": "Abhī", "english": "Now", "category": "Time"},
        {"id": 93, "hindi": "सुबह", "romanization": "Subah", "english": "Morning", "category": "Time"},
        {"id": 94, "hindi": "शाम", "romanization": "Śām", "english": "Evening", "category": "Time"},
        {"id": 95, "hindi": "दोपहर", "romanization": "Dopahar", "english": "Afternoon", "category": "Time"},

        {"id": 96, "hindi": "स्कूल", "romanization": "Skūl", "english": "School", "category": "Places"},
        {"id": 97, "hindi": "बाज़ार", "romanization": "Bāzār", "english": "Market", "category": "Places"},
        {"id": 98, "hindi": "अस्पताल", "romanization": "Aspatāl", "english": "Hospital", "category": "Places"},
        {"id": 99, "hindi": "रास्ता", "romanization": "Rāstā", "english": "Road/Way", "category": "Places"},
        {"id": 100, "hindi": "देश", "romanization": "Deś", "english": "Country", "category": "Places"}
      ]
    },
    {
      "id": 2,
      "name": "Level 2 - Intermediate",
      "description": "Intermediate Hindi vocabulary",
      "flashcards": [
        {"id": 101, "hindi": "ग्यारह", "romanization": "Gyārah", "english": "Eleven", "category": "Numbers"},
        {"id": 102, "hindi": "बारह", "romanization": "Bārah", "english": "Twelve", "category": "Numbers"},
        {"id": 103, "hindi": "तेरह", "romanization": "Terah", "english": "Thirteen", "category": "Numbers"},
        {"id": 104, "hindi": "चौदह", "romanization": "Chaudah", "english": "Fourteen", "category": "Numbers"},
        {"id": 105, "hindi": "पंद्रह", "romanization": "Pandrah", "english": "Fifteen", "category": "Numbers"},
        {"id": 106, "hindi": "सोलह", "romanization": "Solah", "english": "Sixteen", "category": "Numbers"},
        {"id": 107, "hindi": "सत्रह", "romanization": "Satrah", "english": "Seventeen", "category": "Numbers"},
        {"id": 108, "hindi": "अठारह", "romanization": "Aṭhārah", "english": "Eighteen", "category": "Numbers"},
        {"id": 109, "hindi": "उन्नीस", "romanization": "Unnīs", "english": "Nineteen", "category": "Numbers"},
        {"id": 110, "hindi": "बीस", "romanization": "Bīs", "english": "Twenty", "category": "Numbers"},
        {"id": 111, "hindi": "तीस", "romanization": "Tīs", "english": "Thirty", "category": "Numbers"},
        {"id": 112, "hindi": "चालीस", "romanization": "Chālīs", "english": "Forty", "category": "Numbers"},
        {"id": 113, "hindi": "पचास", "romanization": "Pachās", "english": "Fifty", "category": "Numbers"},
        {"id": 114, "hindi": "साठ", "romanization": "Sāṭh", "english": "Sixty", "category": "Numbers"},
        {"id": 115, "hindi": "सत्तर", "romanization": "Sattar", "english": "Seventy", "category": "Numbers"},
        {"id": 116, "hindi": "अस्सी", "romanization": "Assī", "english": "Eighty", "category": "Numbers"},
        {"id": 117, "hindi": "नब्बे", "romanization": "Nabbe", "english": "Ninety", "category": "Numbers"},
        {"id": 118, "hindi": "सौ", "romanization": "Sau", "english": "Hundred", "category": "Numbers"},
        {"id": 119, "hindi": "हज़ार", "romanization": "Hazār", "english": "Thousand", "category": "Numbers"},

        {"id": 120, "hindi": "सोमवार", "romanization": "Somvār", "english": "Monday", "category": "Time"},
        {"id": 121, "hindi": "मंगलवार", "romanization": "Maṅgalvār", "english": "Tuesday", "category": "Time"},
        {"id": 122, "hindi": "बुधवार", "romanization": "Budhvār", "english": "Wednesday", "category": "Time"},
        {"id": 123, "hindi": "गुरुवार", "romanization": "Guruvār", "english": "Thursday", "category": "Time"},
        {"id": 124, "hindi": "शुक्रवार", "romanization": "Śukravār", "english": "Friday", "category": "Time"},
        {"id": 125, "hindi": "शनिवार", "romanization": "Śanivār", "english": "Saturday", "category": "Time"},
        {"id": 126, "hindi": "रविवार", "romanization": "Ravivār", "english": "Sunday", "category": "Time"},
        {"id": 127, "hindi": "सप्ताह", "romanization": "Saptāh", "english": "Week", "category": "Time"},
        {"id": 128, "hindi": "महीना", "romanization": "Mahīnā", "english": "Month", "category": "Time"},
        {"id": 129, "hindi": "साल", "romanization": "Sāl", "english": "Year", "category": "Time"},
        {"id": 130, "hindi": "घंटा", "romanization": "Ghaṇṭā", "english": "Hour", "category": "Time"},
        {"id": 131, "hindi": "मिनट", "romanization": "Minaṭ", "english": "Minute", "category": "Time"},

        {"id": 132, "hindi": "दौड़ना", "romanization": "Dauṛnā", "english": "Run", "category": "Verbs"},
        {"id": 133, "hindi": "चलना", "romanization": "Chalnā", "english": "Walk", "category": "Verbs"},
        {"id": 134, "hindi": "बैठना", "romanization": "Baiṭhnā", "english": "Sit", "category": "Verbs"},
        {"id": 135, "hindi": "खड़ा होना", "romanization": "Khaṛā honā", "english": "Stand", "category": "Verbs"},
        {"id": 136, "hindi": "सीखना", "romanization": "Sīkhnā", "english": "Learn", "category": "Verbs"},
        {"id": 137, "hindi": "सिखाना", "romanization": "Sikhānā", "english": "Teach", "category": "Verbs"},
        {"id": 138, "hindi": "खेलना", "romanization": "Khelnā", "english": "Play", "category": "Verbs"},
        {"id": 139, "hindi": "काम करना", "romanization": "Kām karnā", "english": "Work", "category": "Verbs"},
        {"id": 140, "hindi": "हँसना", "romanization": "Haṅsnā", "english": "Laugh", "category": "Verbs"},
        {"id": 141, "hindi": "रोना", "romanization": "Ronā", "english": "Cry", "category": "Verbs"},
        {"id": 142, "hindi": "गाना", "romanization": "Gānā", "english": "Sing", "category": "Verbs"},
        {"id": 143, "hindi": "नाचना", "romanization": "Nāchnā", "english": "Dance", "category": "Verbs"},
        {"id": 144, "hindi": "खरीदना", "romanization": "Kharīdnā", "english": "Buy", "category": "Verbs"},
        {"id": 145, "hindi": "बेचना", "romanization": "Bechnā", "english": "Sell", "category": "Verbs"},

        {"id": 146, "hindi": "रोटी", "romanization": "Roṭī", "english": "Bread/Roti", "category": "Food"},
        {"id": 147, "hindi": "चावल", "romanization": "Chāval", "english": "Rice", "category": "Food"},
        {"id": 148, "hindi": "दाल", "romanization": "Dāl", "english": "Lentils", "category": "Food"},
        {"id": 149, "hindi": "सब्ज़ी", "romanization": "Sabzī", "english": "Vegetable", "category": "Food"},
        {"id": 150, "hindi": "फल", "romanization": "Phal", "english": "Fruit", "category": "Food"},
        {"id": 151, "hindi": "दूध", "romanization": "Dūdh", "english": "Milk", "category": "Food"},
        {"id": 152, "hindi": "चाय", "romanization": "Chāy", "english": "Tea", "category": "Food"},
        {"id": 153, "hindi": "कॉफ़ी", "romanization": "Kŏfī", "english": "Coffee", "category": "Food"},
        {"id": 154, "hindi": "नमक", "romanization": "Namak", "english": "Salt", "category": "Food"},
        {"id": 155, "hindi": "चीनी", "romanization": "Chīnī", "english": "Sugar", "category": "Food"},
        {"id": 156, "hindi": "मिर्च", "romanization": "Mirch", "english": "Chili/Pepper", "category": "Food"},
        {"id": 157, "hindi": "तेल", "romanization": "Tel", "english": "Oil", "category": "Food"},

        {"id": 158, "hindi": "कपड़े", "romanization": "Kapṛe", "english": "Clothes", "category": "Clothing"},
        {"id": 159, "hindi": "कमीज़", "romanization": "Kamīz", "english": "Shirt", "category": "Clothing"},
        {"id": 160, "hindi": "पैंट", "romanization": "Paiṇṭ", "english": "Pants", "category": "Clothing"},
        {"id": 161, "hindi": "साड़ी", "romanization": "Sāṛī", "english": "Saree", "category": "Clothing"},
        {"id": 162, "hindi": "जूते", "romanization": "Jūte", "english": "Shoes", "category": "Clothing"},
        {"id": 163, "hindi": "टोपी", "romanization": "Ṭopī", "english": "Hat/Cap", "category": "Clothing"},

        {"id": 164, "hindi": "उँगली", "romanization": "Uṅglī", "english": "Finger", "category": "Body Parts"},
        {"id": 165, "hindi": "गर्दन", "romanization": "Gardan", "english": "Neck", "category": "Body Parts"},
        {"id": 166, "hindi": "पीठ", "romanization": "Pīṭh", "english": "Back", "category": "Body Parts"},
        {"id": 167, "hindi": "पेट", "romanization": "Peṭ", "english": "Stomach", "category": "Body Parts"},
        {"id": 168, "hindi": "दिल", "romanization": "Dil", "english": "Heart", "category": "Body Parts"},
        {"id": 169, "hindi": "दाँत", "romanization": "Dāṅt", "english": "Tooth", "category": "Body Parts"},
        {"id": 170, "hindi": "बाल", "romanization": "Bāl", "english": "Hair", "category": "Body Parts"},

        {"id": 171, "hindi": "शहर", "romanization": "Śahar", "english": "City", "category": "Places"},
        {"id": 172, "hindi": "गाँव", "romanization": "Gāṅv", "english": "Village", "category": "Places"},
        {"id": 173, "hindi": "दफ़्तर", "romanization": "Daftar", "english": "Office", "category": "Places"},
        {"id": 174, "hindi": "होटल", "romanization": "Hoṭel", "english": "Hotel/Restaurant", "category": "Places"},
        {"id": 175, "hindi": "पार्क", "romanization": "Pārk", "english": "Park", "category": "Places"},
        {"id": 176, "hindi": "मंदिर", "romanization": "Mandir", "english": "Temple", "category": "Places"},
        {"id": 177, "hindi": "स्टेशन", "romanization": "Sṭeśan", "english": "Station", "category": "Places"},
        {"id": 178, "hindi": "हवाई अड्डा", "romanization": "Havāī aḍḍā", "english": "Airport", "category": "Places"},

        {"id": 179, "hindi": "तेज़", "romanization": "Tez", "english": "Fast", "category": "Adjectives"},
        {"id": 180, "hindi": "धीमा", "romanization": "Dhīmā", "english": "Slow", "category": "Adjectives"},
        {"id": 181, "hindi": "ऊँचा", "romanization": "Ūṅchā", "english": "High/Tall", "category": "Adjectives"},
        {"id": 182, "hindi": "नीचा", "romanization": "Nīchā", "english": "Low/Short", "category": "Adjectives"},
        {"id": 183, "hindi": "मोटा", "romanization": "Moṭā", "english": "Fat/Thick", "category": "Adjectives"},
        {"id": 184, "hindi": "पतला", "romanization": "Patlā", "english": "Thin", "category": "Adjectives"},
        {"id": 185, "hindi": "साफ़", "romanization": "Sāf", "english": "Clean", "category": "Adjectives"},
        {"id": 186, "hindi": "गंदा", "romanization": "Gandā", "english": "Dirty", "category": "Adjectives"},
        {"id": 187, "hindi": "खुश", "romanization": "Khuś", "english": "Happy", "category": "Adjectives"},
        {"id": 188, "hindi": "दुखी", "romanization": "Dukhī", "english": "Sad", "category": "Adjectives"},

        {"id": 189, "hindi": "किताब", "romanization": "Kitāb", "english": "Book", "category": "Common Words"},
        {"id": 190, "hindi": "कलम", "romanization": "Kalam", "english": "Pen", "category": "Common Words"},
        {"id": 191, "hindi": "कागज़", "romanization": "Kāgaz", "english": "Paper", "category": "Common Words"},
        {"id": 192, "hindi": "कुर्सी", "romanization": "Kursī", "english": "Chair", "category": "Common Words"},
        {"id": 193, "hindi": "मेज़", "romanization": "Mez", "english": "Table", "category": "Common Words"},
        {"id": 194, "hindi": "दरवाज़ा", "romanization": "Darvāzā", "english": "Door", "category": "Common Words"},
        {"id": 195, "hindi": "खिड़की", "romanization": "Khiṛkī", "english": "Window", "category": "Common Words"},
        {"id": 196, "hindi": "पैसा", "romanization": "Paisā", "english": "Money", "category": "Common Words"},
        {"id": 197, "hindi": "काम", "romanization": "Kām", "english": "Work/Task", "category": "Common Words"},
        {"id": 198, "hindi": "बात", "romanization": "Bāt", "english": "Talk/Matter", "category": "Common Words"},
        {"id": 199, "hindi": "दोस्त", "romanization": "Dost", "english": "Friend", "category": "Common Words"},
        {"id": 200, "hindi": "प्यार", "romanization": "Pyār", "english": "Love", "category": "Common Words"}
      ]
    },
    {
      "id": 3,
      "name": "Level 3 - Numbers 1-100",
      "description": "Complete number vocabulary from 1 to 100 in Hindi",
      "flashcards": [
        {"id": 201, "hindi": "एक", "romanization": "Ek", "english": "1", "category": "Numbers"},
        {"id": 202, "hindi": "दो", "romanization": "Do", "english": "2", "category": "Numbers"},
        {"id": 203, "hindi": "तीन", "romanization": "Tīn", "english": "3", "category": "Numbers"},
        {"id": 204, "hindi": "चार", "romanization": "Chār", "english": "4", "category": "Numbers"},
        {"id": 205, "hindi": "पाँच", "romanization": "Pāṅch", "english": "5", "category": "Numbers"},
        {"id": 206, "hindi": "छह", "romanization": "Chhah", "english": "6", "category": "Numbers"},
        {"id": 207, "hindi": "सात", "romanization": "Sāt", "english": "7", "category": "Numbers"},
        {"id": 208, "hindi": "आठ", "romanization": "Āṭh", "english": "8", "category": "Numbers"},
        {"id": 209, "hindi": "नौ", "romanization": "Nau", "english": "9", "category": "Numbers"},
        {"id": 210, "hindi": "दस", "romanization": "Das", "english": "10", "category": "Numbers"},
        {"id": 211, "hindi": "ग्यारह", "romanization": "Gyārah", "english": "11", "category": "Numbers"},
        {"id": 212, "hindi": "बारह", "romanization": "Bārah", "english": "12", "category": "Numbers"},
        {"id": 213, "hindi": "तेरह", "romanization": "Terah", "english": "13", "category": "Numbers"},
        {"id": 214, "hindi": "चौदह", "romanization": "Chaudah", "english": "14", "category": "Numbers"},
        {"id": 215, "hindi": "पंद्रह", "romanization": "Pandrah", "english": "15", "category": "Numbers"},
        {"id": 216, "hindi": "सोलह", "romanization": "Solah", "english": "16", "category": "Numbers"},
        {"id": 217, "hindi": "सत्रह", "romanization": "Satrah", "english": "17", "category": "Numbers"},
        {"id": 218, "hindi": "अठारह", "romanization": "Aṭhārah", "english": "18", "category": "Numbers"},
        {"id": 219, "hindi": "उन्नीस", "romanization": "Unnīs", "english": "19", "category": "Numbers"},
        {"id": 220, "hindi": "बीस", "romanization": "Bīs", "english": "20", "category": "Numbers"},
        {"id": 221, "hindi": "इक्कीस", "romanization": "Ikkīs", "english": "21", "category": "Numbers"},
        {"id": 222, "hindi": "बाईस", "romanization": "Bāīs", "english": "22", "category": "Numbers"},
        {"id": 223, "hindi": "तेईस", "romanization": "Teīs", "english": "23", "category": "Numbers"},
        {"id": 224, "hindi": "चौबीस", "romanization": "Chaubīs", "english": "24", "category": "Numbers"},
        {"id": 225, "hindi": "पच्चीस", "romanization": "Pachchīs", "english": "25", "category": "Numbers"},
        {"id": 226, "hindi": "छब्बीस", "romanization": "Chhabbīs", "english": "26", "category": "Numbers"},
        {"id": 227, "hindi": "सत्ताईस", "romanization": "Sattāīs", "english": "27", "category": "Numbers"},
        {"id": 228, "hindi": "अट्ठाईस", "romanization": "Aṭṭhāīs", "english": "28", "category": "Numbers"},
        {"id": 229, "hindi": "उनतीस", "romanization": "Unatīs", "english": "29", "category": "Numbers"},
        {"id": 230, "hindi": "तीस", "romanization": "Tīs", "english": "30", "category": "Numbers"},
        {"id": 231, "hindi": "इकतीस", "romanization": "Ikatīs", "english": "31", "category": "Numbers"},
        {"id": 232, "hindi": "बत्तीस", "romanization": "Battīs", "english": "32", "category": "Numbers"},
        {"id": 233, "hindi": "तैंतीस", "romanization": "Taiṅtīs", "english": "33", "category": "Numbers"},
        {"id": 234, "hindi": "चौंतीस", "romanization": "Chauṅtīs", "english": "34", "category": "Numbers"},
        {"id": 235, "hindi": "पैंतीस", "romanization": "Paiṅtīs", "english": "35", "category": "Numbers"},
        {"id": 236, "hindi": "छत्तीस", "romanization": "Chhattīs", "english": "36", "category": "Numbers"},
        {"id": 237, "hindi": "सैंतीस", "romanization": "Saiṅtīs", "english": "37", "category": "Numbers"},
        {"id": 238, "hindi": "अड़तीस", "romanization": "Aṛtīs", "english": "38", "category": "Numbers"},
        {"id": 239, "hindi": "उनतालीस", "romanization": "Unatālīs", "english": "39", "category": "Numbers"},
        {"id": 240, "hindi": "चालीस", "romanization": "Chālīs", "english": "40", "category": "Numbers"},
        {"id": 241, "hindi": "इकतालीस", "romanization": "Ikatālīs", "english": "41", "category": "Numbers"},
        {"id": 242, "hindi": "बयालीस", "romanization": "Bayālīs", "english": "42", "category": "Numbers"},
        {"id": 243, "hindi": "तैंतालीस", "romanization": "Taiṅtālīs", "english": "43", "category": "Numbers"},
        {"id": 244, "hindi": "चवालीस", "romanization": "Chavālīs", "english": "44", "category": "Numbers"},
        {"id": 245, "hindi": "पैंतालीस", "romanization": "Paiṅtālīs", "english": "45", "category": "Numbers"},
        {"id": 246, "hindi": "छियालीस", "romanization": "Chhiyālīs", "english": "46", "category": "Numbers"},
        {"id": 247, "hindi": "सैंतालीस", "romanization": "Saiṅtālīs", "english": "47", "category": "Numbers"},
        {"id": 248, "hindi": "अड़तालीस", "romanization": "Aṛtālīs", "english": "48", "category": "Numbers"},
        {"id": 249, "hindi": "उनचास", "romanization": "Unachās", "english": "49", "category": "Numbers"},
        {"id": 250, "hindi": "पचास", "romanization": "Pachās", "english": "50", "category": "Numbers"},
        {"id": 251, "hindi": "इक्यावन", "romanization": "Ikyāvan", "english": "51", "category": "Numbers"},
        {"id": 252, "hindi": "बावन", "romanization": "Bāvan", "english": "52", "category": "Numbers"},
        {"id": 253, "hindi": "तिरपन", "romanization": "Tirapan", "english": "53", "category": "Numbers"},
        {"id": 254, "hindi": "चौवन", "romanization": "Chauvan", "english": "54", "category": "Numbers"},
        {"id": 255, "hindi": "पचपन", "romanization": "Pachapan", "english": "55", "category": "Numbers"},
        {"id": 256, "hindi": "छप्पन", "romanization": "Chhappan", "english": "56", "category": "Numbers"},
        {"id": 257, "hindi": "सत्तावन", "romanization": "Sattāvan", "english": "57", "category": "Numbers"},
        {"id": 258, "hindi": "अट्ठावन", "romanization": "Aṭṭhāvan", "english": "58", "category": "Numbers"},
        {"id": 259, "hindi": "उनसठ", "romanization": "Unasaṭh", "english": "59", "category": "Numbers"},
        {"id": 260, "hindi": "साठ", "romanization": "Sāṭh", "english": "60", "category": "Numbers"},
        {"id": 261, "hindi": "इकसठ", "romanization": "Ikasaṭh", "english": "61", "category": "Numbers"},
        {"id": 262, "hindi": "बासठ", "romanization": "Bāsaṭh", "english": "62", "category": "Numbers"},
        {"id": 263, "hindi": "तिरसठ", "romanization": "Tirasaṭh", "english": "63", "category": "Numbers"},
        {"id": 264, "hindi": "चौंसठ", "romanization": "Chauṅsaṭh", "english": "64", "category": "Numbers"},
        {"id": 265, "hindi": "पैंसठ", "romanization": "Paiṅsaṭh", "english": "65", "category": "Numbers"},
        {"id": 266, "hindi": "छियासठ", "romanization": "Chhiyāsaṭh", "english": "66", "category": "Numbers"},
        {"id": 267, "hindi": "सड़सठ", "romanization": "Saṛsaṭh", "english": "67", "category": "Numbers"},
        {"id": 268, "hindi": "अड़सठ", "romanization": "Aṛsaṭh", "english": "68", "category": "Numbers"},
        {"id": 269, "hindi": "उनहत्तर", "romanization": "Unahattar", "english": "69", "category": "Numbers"},
        {"id": 270, "hindi": "सत्तर", "romanization": "Sattar", "english": "70", "category": "Numbers"},
        {"id": 271, "hindi": "इकहत्तर", "romanization": "Ikahattar", "english": "71", "category": "Numbers"},
        {"id": 272, "hindi": "बहत्तर", "romanization": "Bahattar", "english": "72", "category": "Numbers"},
        {"id": 273, "hindi": "तिहत्तर", "romanization": "Tihattar", "english": "73", "category": "Numbers"},
        {"id": 274, "hindi": "चौहत्तर", "romanization": "Chauhattar", "english": "74", "category": "Numbers"},
        {"id": 275, "hindi": "पचहत्तर", "romanization": "Pachahattar", "english": "75", "category": "Numbers"},
        {"id": 276, "hindi": "छिहत्तर", "romanization": "Chhihattar", "english": "76", "category": "Numbers"},
        {"id": 277, "hindi": "सतहत्तर", "romanization": "Satahattar", "english": "77", "category": "Numbers"},
        {"id": 278, "hindi": "अठहत्तर", "romanization": "Aṭhahattar", "english": "78", "category": "Numbers"},
        {"id": 279, "hindi": "उनासी", "romanization": "Unāsī", "english": "79", "category": "Numbers"},
        {"id": 280, "hindi": "अस्सी", "romanization": "Assī", "english": "80", "category": "Numbers"},
        {"id": 281, "hindi": "इक्यासी", "romanization": "Ikyāsī", "english": "81", "category": "Numbers"},
        {"id": 282, "hindi": "बयासी", "romanization": "Bayāsī", "english": "82", "category": "Numbers"},
        {"id": 283, "hindi": "तिरासी", "romanization": "Tirāsī", "english": "83", "category": "Numbers"},
        {"id": 284, "hindi": "चौरासी", "romanization": "Chaurāsī", "english": "84", "category": "Numbers"},
        {"id": 285, "hindi": "पचासी", "romanization": "Pachāsī", "english": "85", "category": "Numbers"},
        {"id": 286, "hindi": "छियासी", "romanization": "Chhiyāsī", "english": "86", "category": "Numbers"},
        {"id": 287, "hindi": "सत्तासी", "romanization": "Sattāsī", "english": "87", "category": "Numbers"},
        {"id": 288, "hindi": "अट्ठासी", "romanization": "Aṭṭhāsī", "english": "88", "category": "Numbers"},
        {"id": 289, "hindi": "नवासी", "romanization": "Navāsī", "english": "89", "category": "Numbers"},
        {"id": 290, "hindi": "नब्बे", "romanization": "Nabbe", "english": "90", "category": "Numbers"},
        {"id": 291, "hindi": "इक्यानवे", "romanization": "Ikyānave", "english": "91", "category": "Numbers"},
        {"id": 292, "hindi": "बानवे", "romanization": "Bānave", "english": "92", "category": "Numbers"},
        {"id": 293, "hindi": "तिरानवे", "romanization": "Tirānave", "english": "93", "category": "Numbers"},
        {"id": 294, "hindi": "चौरानवे", "romanization": "Chaurānave", "english": "94", "category": "Numbers"},
        {"id": 295, "hindi": "पचानवे", "romanization": "Pachānave", "english": "95", "category": "Numbers"},
        {"id": 296, "hindi": "छियानवे", "romanization": "Chhiyānave", "english": "96", "category": "Numbers"},
        {"id": 297, "hindi": "सत्तानवे", "romanization": "Sattānave", "english": "97", "category": "Numbers"},
        {"id": 298, "hindi": "अट्ठानवे", "romanization": "Aṭṭhānave", "english": "98", "category": "Numbers"},
        {"id": 299, "hindi": "निन्यानवे", "romanization": "Ninyānave", "english": "99", "category": "Numbers"},
        {"id": 300, "hindi": "सौ", "romanization": "Sau", "english": "100", "category": "Numbers"}
      ]
    }
  ]
};
